import type { Language } from '../i18n'

// ---------------------------------------------------------------------------
// URL slug mapping for 14 main stars (Pinyin romanization)
// ---------------------------------------------------------------------------

export const STAR_SLUGS: Record<string, string> = {
  '紫微': 'zi-wei',
  '天機': 'tian-ji',
  '太陽': 'tai-yang',
  '武曲': 'wu-qu',
  '天同': 'tian-tong',
  '廉貞': 'lian-zhen',
  '天府': 'tian-fu',
  '太陰': 'tai-yin',
  '貪狼': 'tan-lang',
  '巨門': 'ju-men',
  '天相': 'tian-xiang',
  '天梁': 'tian-liang',
  '七殺': 'qi-sha',
  '破軍': 'po-jun',
}

export const SLUG_TO_STAR: Record<string, string> = Object.fromEntries(
  Object.entries(STAR_SLUGS).map(([k, v]) => [v, k])
)

export const ALL_STAR_SLUGS = Object.values(STAR_SLUGS)

// ---------------------------------------------------------------------------
// Star content type & data (4 languages)
// ---------------------------------------------------------------------------

export const STAR_CONTENT: Record<string, Record<Language, {
  name: string
  nickname: string
  element: string
  series: string
  overview: string
  personality: string
  career: string
  relationship: string
  sihua: string
  companion: string
}>> = {
  '紫微': {
    ko: {
      name: '자미성(紫微星)',
      nickname: '제왕의 별',
      element: '토(土)',
      series: '자미 계열',
      overview: '자미성은 자미두수에서 가장 핵심이 되는 별로, 모든 별의 중심에 위치합니다. 제왕의 격을 지니며 타고난 리더십과 위엄을 상징합니다. 명반에서 자미성의 위치에 따라 나머지 13개 주성의 배치가 결정되므로, 명리학적으로 가장 중요한 별입니다.',
      personality: '자미성이 명궁에 있으면 타고난 리더십과 자존심이 강합니다. 주변 사람들을 자연스럽게 이끄는 카리스마가 있으며, 권위와 품격을 중시합니다. 다만 지나친 자존심으로 인해 외로워질 수 있으며, 타인의 조언을 잘 받아들이지 않는 경향이 있습니다.',
      career: '경영, 관리직, 정치 등 사람 위에 서는 직업에서 두각을 나타냅니다. 조직의 수장이나 독립적인 사업가로서 성공할 가능성이 높으며, 남에게 지시받는 위치보다는 결정권을 가진 자리가 적합합니다.',
      relationship: '연애에서도 주도권을 쥐려 하며, 상대방에 대한 기대치가 높습니다. 품격 있고 능력 있는 파트너를 선호하며, 존경받고 싶은 욕구가 강합니다. 배우자궁의 다른 별과의 조합에 따라 관계의 양상이 크게 달라집니다.',
      sihua: '화록(化祿)이 되면 관대하고 베풀기 좋아하는 부귀한 리더가 됩니다. 화권(化權)이면 절대적 권위와 통솔력을 발휘합니다. 화과(化科)면 명성과 학문적 권위를 얻습니다. 화기(化忌)가 되면 고독한 권력자가 되어 주변에 사람이 떠나갈 수 있습니다.',
      companion: '천부(天府)와 동궁하면 재왕합벽(帝王合璧)이라 하여 부귀와 권력을 모두 갖습니다. 탐랑(貪狼)과 만나면 욕망과 권력이 결합하여 복잡한 양상을 보이며, 천상(天相)과 함께하면 현명한 보좌를 얻어 안정적입니다.',
    },
    en: {
      name: 'Zi Wei Star (Purple Star)',
      nickname: 'The Emperor Star',
      element: 'Earth',
      series: 'Zi Wei Series',
      overview: 'Zi Wei is the most crucial star in Zi Wei Dou Shu, sitting at the center of all stars. It symbolizes imperial authority, innate leadership, and dignity. The positions of all other 13 main stars are determined by Zi Wei\'s placement on the chart.',
      personality: 'With Zi Wei in the Life Palace, you possess natural leadership and strong self-esteem. You have charisma that naturally draws people to follow you, and you value authority and prestige. However, excessive pride may lead to isolation, and you tend to resist others\' advice.',
      career: 'You excel in management, executive roles, and politics — positions of authority. You are likely to succeed as an organizational leader or independent entrepreneur, preferring decision-making roles over subordinate positions.',
      relationship: 'In relationships, you tend to take the lead and have high expectations for your partner. You prefer sophisticated and capable partners and have a strong desire to be respected. The dynamics vary greatly depending on companion stars in the Spouse Palace.',
      sihua: 'When transformed by Lu (Wealth), you become a generous and magnanimous leader of wealth. Quan (Power) transformation grants absolute authority and commanding presence. Ke (Fame) brings scholarly reputation and public recognition. Ji (Obstruction) may create a lonely ruler whose authority drives others away.',
      companion: 'Paired with Tian Fu, it forms the "Emperor-Treasury" combination signifying both wealth and power. With Tan Lang, desire merges with authority creating complex dynamics. With Tian Xiang, wise counsel brings stability.',
    },
    ja: {
      name: '紫微星(しびせい)',
      nickname: '帝王の星',
      element: '土',
      series: '紫微系',
      overview: '紫微星は紫微斗数において最も重要な星であり、全ての星の中心に位置します。帝王の格を持ち、生まれながらのリーダーシップと威厳を象徴します。命盤において紫微星の位置により、残りの13主星の配置が決定されます。',
      personality: '紫微星が命宮にある場合、生まれながらのリーダーシップと強い自尊心を持ちます。周囲の人々を自然に導くカリスマがあり、権威と品格を重視します。ただし、過度なプライドにより孤立する可能性があり、他者の助言を受け入れにくい傾向があります。',
      career: '経営、管理職、政治など、人の上に立つ職業で頭角を現します。組織のトップや独立した起業家として成功する可能性が高く、指示を受ける立場よりも決定権を持つポジションが適しています。',
      relationship: '恋愛でも主導権を握ろうとし、相手への期待が高いです。品格があり能力のあるパートナーを好み、尊敬されたいという欲求が強いです。配偶者宮の他の星との組み合わせにより関係の様相が大きく変わります。',
      sihua: '化禄になると寛大で施しを好む富貴なリーダーとなります。化権では絶対的な権威と統率力を発揮します。化科では名声と学問的権威を得ます。化忌になると孤独な権力者となり、周囲の人が離れていく可能性があります。',
      companion: '天府と同宮すると帝王合璧と呼ばれ、富と権力の両方を手にします。貪狼と出会うと欲望と権力が結合し複雑な様相を見せます。天相と共にあると賢明な補佐を得て安定します。',
    },
    zh: {
      name: '紫微星',
      nickname: '帝王之星',
      element: '土',
      series: '紫微系',
      overview: '紫微星是紫微斗数中最核心的主星，位居所有星曜的中心。它象征帝王之格，代表与生俱来的领导力与威严。命盘中紫微星的位置决定了其余13颗主星的排列，因此在命理学上具有最重要的地位。',
      personality: '紫微星坐命宫的人天生具备领导才能和强烈的自尊心。拥有自然而然吸引众人追随的魅力，注重权威与品格。但过度的自尊可能导致孤立，且不太容易接受他人的建议。',
      career: '适合经营管理、高层管理、政治等居于人上的职业。作为组织领导者或独立创业者成功的可能性很高，比起接受指示的位置，更适合拥有决策权的岗位。',
      relationship: '在感情中也倾向于掌握主导权，对伴侣的期望较高。偏好有品味且有能力的伴侣，有强烈的被尊重需求。根据配偶宫中其他星曜的组合，关系的面貌会有很大差异。',
      sihua: '化禄时成为慷慨大方、乐善好施的富贵领袖。化权则发挥绝对的权威和统率力。化科带来名声和学术权威。化忌则可能成为孤独的掌权者，身边的人逐渐疏远。',
      companion: '与天府同宫称为帝王合璧，同时拥有财富与权力。与贪狼相遇则欲望与权力结合，呈现复杂面貌。与天相同宫则获得贤明辅佐，局面稳定。',
    },
  },
  '天機': {
    ko: {
      name: '천기성(天機星)',
      nickname: '지략가의 별',
      element: '목(木)',
      series: '자미 계열',
      overview: '천기성은 지혜와 기획력을 상징하는 별로, 머리가 비상하고 변화에 민감합니다. 모든 상황을 분석하고 전략을 세우는 데 뛰어난 재능을 보이며, 유연한 사고력이 가장 큰 장점입니다.',
      personality: '명궁에 천기성이 있으면 총명하고 분석적인 사고를 가집니다. 새로운 것을 빠르게 학습하며 변화를 두려워하지 않습니다. 다만 너무 많은 생각으로 우유부단해질 수 있으며, 한 가지에 집중하기보다 여러 가지를 동시에 추구하는 경향이 있습니다.',
      career: '기획, 컨설팅, IT, 연구 등 두뇌를 활용하는 직업에 적합합니다. 전략적 사고가 필요한 분야에서 두각을 나타내며, 창의적인 문제 해결 능력이 핵심 경쟁력입니다.',
      relationship: '연애에서 지적인 교감을 중시하며, 대화가 통하는 상대를 선호합니다. 감정 표현에 서툰 편이라 상대방이 답답해할 수 있으며, 관계에서도 분석적으로 접근하는 경향이 있습니다.',
      sihua: '화록이면 지혜로 재물을 모으는 재능이 있습니다. 화권이면 결단력 있는 전략가로 변모합니다. 화과면 학문적 명성과 연구 업적을 이룹니다. 화기가 되면 과도한 사고와 계산으로 심리적 불안에 시달립니다.',
      companion: '태음(太陰)과 동궁하면 감성과 지성이 조화를 이루어 예술적 재능이 빛납니다. 천량(天梁)과 함께하면 지혜에 원숙함이 더해져 안정적이며, 거문(巨門)과 만나면 논쟁과 분석이 극대화됩니다.',
    },
    en: {
      name: 'Tian Ji Star (Heavenly Secret)',
      nickname: 'The Strategist Star',
      element: 'Wood',
      series: 'Zi Wei Series',
      overview: 'Tian Ji symbolizes wisdom and strategic planning. It represents a sharp mind sensitive to change, with exceptional talent for analysis and strategy. Flexible thinking is its greatest strength.',
      personality: 'With Tian Ji in the Life Palace, you possess brilliant analytical thinking. You learn new things quickly and don\'t fear change. However, overthinking may lead to indecisiveness, and you tend to pursue multiple interests simultaneously rather than focusing on one.',
      career: 'Suited for careers utilizing intellect — planning, consulting, IT, and research. You stand out in fields requiring strategic thinking, with creative problem-solving as your core competitive advantage.',
      relationship: 'You value intellectual connection in relationships, preferring partners with stimulating conversation. You may struggle with emotional expression, which can frustrate partners, and tend to approach relationships analytically.',
      sihua: 'Lu transformation brings talent for accumulating wealth through wisdom. Quan grants decisive strategic power. Ke brings academic fame and research achievements. Ji causes psychological anxiety from excessive thinking and calculation.',
      companion: 'Paired with Tai Yin, emotion and intellect harmonize, highlighting artistic talent. With Tian Liang, maturity complements wisdom for stability. With Ju Men, debate and analysis are maximized.',
    },
    ja: {
      name: '天機星(てんきせい)',
      nickname: '策略家の星',
      element: '木',
      series: '紫微系',
      overview: '天機星は知恵と企画力を象徴する星で、頭脳明晰で変化に敏感です。あらゆる状況を分析し戦略を立てることに優れた才能を見せ、柔軟な思考力が最大の長所です。',
      personality: '命宮に天機星がある場合、聡明で分析的な思考を持ちます。新しいことを素早く学び、変化を恐れません。ただし、考えすぎて優柔不断になることがあり、一つに集中するよりも複数のことを同時に追求する傾向があります。',
      career: '企画、コンサルティング、IT、研究など頭脳を活用する職業に適しています。戦略的思考が必要な分野で頭角を現し、創造的な問題解決能力が核心的な競争力です。',
      relationship: '恋愛では知的な交流を重視し、会話が合う相手を好みます。感情表現が苦手なため相手がもどかしく感じることがあり、関係においても分析的にアプローチする傾向があります。',
      sihua: '化禄では知恵で財を集める才能があります。化権では決断力のある策略家に変わります。化科では学問的名声と研究業績を成し遂げます。化忌では過度な思考と計算により心理的不安に悩まされます。',
      companion: '太陰と同宮すると感性と知性が調和し芸術的才能が輝きます。天梁と共にあると知恵に円熟さが加わり安定します。巨門と出会うと論争と分析が極大化されます。',
    },
    zh: {
      name: '天机星',
      nickname: '谋略之星',
      element: '木',
      series: '紫微系',
      overview: '天机星象征智慧与策划能力，头脑敏锐且对变化十分敏感。在分析各种状况和制定策略方面展现出非凡的才华，灵活的思维方式是其最大的优势。',
      personality: '天机星坐命宫者聪慧且具有分析性思维。能快速学习新事物，不惧怕变化。但可能因想得太多而变得优柔寡断，倾向于同时追求多个方向而非专注于一件事。',
      career: '适合策划、咨询、IT、研究等运用头脑的职业。在需要战略思维的领域中脱颖而出，创造性的问题解决能力是核心竞争力。',
      relationship: '在感情中重视智识上的交流，偏好能够深入对话的伴侣。不太善于表达情感，可能让对方感到郁闷，在关系中也倾向于以分析的方式来处理。',
      sihua: '化禄时拥有以智慧聚财的才能。化权则变为果断的策略家。化科带来学术声望和研究成就。化忌则因过度思虑和计较而饱受心理焦虑。',
      companion: '与太阴同宫时感性与理性和谐交融，艺术才华闪耀。与天梁同宫则智慧之上更添成熟稳重。与巨门相遇则辩论和分析能力达到极致。',
    },
  },
  '太陽': {
    ko: {
      name: '태양성(太陽星)',
      nickname: '빛나는 별',
      element: '화(火)',
      series: '자미 계열',
      overview: '태양성은 광명과 열정을 상징하며, 만물을 비추는 태양처럼 따뜻하고 관대한 성품을 나타냅니다. 공적인 영역에서 빛을 발하며, 봉사 정신과 명예를 중시하는 별입니다.',
      personality: '명궁의 태양성은 밝고 적극적인 성격을 부여합니다. 정의감이 강하고 남을 돕는 것을 좋아하며, 사교적이고 인맥이 넓습니다. 그러나 자신의 에너지를 지나치게 소모하여 번아웃에 빠지기 쉽고, 가까운 사람에게는 오히려 소홀해질 수 있습니다.',
      career: '공공서비스, 교육, 미디어, 정치 등 사회적 영향력이 큰 분야에서 활약합니다. 이름이 알려지는 것을 두려워하지 않으며, 대중 앞에 서는 직업에서 자연스러운 카리스마를 발휘합니다.',
      relationship: '연애에서 헌신적이고 따뜻하지만, 자기 사람보다 바깥 사람에게 더 친절할 수 있습니다. 모두에게 빛을 비추려 하기에 파트너가 질투를 느낄 수 있으며, 화려한 연애보다는 신뢰를 기반으로 한 관계가 필요합니다.',
      sihua: '화록이면 인기와 명성을 통해 재물을 모읍니다. 화권이면 강력한 리더십으로 공적 영역을 이끕니다. 화과면 대중적 명성과 좋은 평판을 얻습니다. 화기가 되면 과도한 소진과 번아웃, 명예 훼손의 위험이 있습니다.',
      companion: '거문(巨門)과 동궁하면 빛과 그림자가 공존하여 논쟁 속에서도 진실을 밝힙니다. 태음(太陰)과 대조적 관계로 음양이 조화를 이루며, 천량(天梁)과 함께하면 명예와 지혜가 결합합니다.',
    },
    en: {
      name: 'Tai Yang Star (The Sun)',
      nickname: 'The Radiant Star',
      element: 'Fire',
      series: 'Zi Wei Series',
      overview: 'Tai Yang symbolizes brilliance and passion, representing warm and generous qualities like the sun illuminating all things. It shines in public domains, valuing service and honor.',
      personality: 'Tai Yang in the Life Palace grants a bright and proactive personality. You have a strong sense of justice, enjoy helping others, and are socially well-connected. However, you may burn out from excessive energy expenditure and can neglect those closest to you.',
      career: 'You thrive in fields with significant social influence — public service, education, media, and politics. You are comfortable in the spotlight and exhibit natural charisma in public-facing roles.',
      relationship: 'Devoted and warm in relationships, but you may show more kindness to outsiders than your own partner. Your desire to shine for everyone may trigger partner jealousy; trust-based relationships work best for you.',
      sihua: 'Lu brings wealth through popularity and fame. Quan grants powerful leadership in public spheres. Ke brings public reputation and good standing. Ji risks burnout, exhaustion, and reputation damage.',
      companion: 'With Ju Men, light and shadow coexist, revealing truth through debate. With Tai Yin, yin-yang balance is achieved. With Tian Liang, honor and wisdom unite.',
    },
    ja: {
      name: '太陽星(たいようせい)',
      nickname: '輝く星',
      element: '火',
      series: '紫微系',
      overview: '太陽星は光明と情熱を象徴し、万物を照らす太陽のように温かく寛大な性質を表します。公的な領域で輝きを放ち、奉仕精神と名誉を重視する星です。',
      personality: '命宮の太陽星は明るく積極的な性格を与えます。正義感が強く人助けが好きで、社交的で人脈が広いです。しかし、エネルギーを使い果たしてバーンアウトに陥りやすく、身近な人にはかえっておろそかになることがあります。',
      career: '公共サービス、教育、メディア、政治など社会的影響力の大きい分野で活躍します。注目されることを恐れず、大衆の前に立つ職業で自然なカリスマを発揮します。',
      relationship: '恋愛では献身的で温かいですが、身内よりも外の人に親切になりがちです。全ての人に光を当てようとするためパートナーが嫉妬を感じることがあり、信頼に基づいた関係が必要です。',
      sihua: '化禄では人気と名声を通じて財を集めます。化権では強力なリーダーシップで公的領域を導きます。化科では大衆的名声と良い評判を得ます。化忌では過度な消耗とバーンアウト、名誉毀損のリスクがあります。',
      companion: '巨門と同宮すると光と影が共存し、論争の中でも真実を明らかにします。太陰とは対照的な関係で陰陽の調和を成し、天梁と共にあると名誉と知恵が結合します。',
    },
    zh: {
      name: '太阳星',
      nickname: '光辉之星',
      element: '火',
      series: '紫微系',
      overview: '太阳星象征光明与热情，如太阳普照万物般温暖慷慨。在公共领域发光发热，重视奉献精神与名誉。',
      personality: '太阳星坐命宫赋予明朗积极的性格。正义感强，乐于助人，善于社交且人脉广泛。但容易因过度消耗能量而陷入倦怠，对身边亲近的人反而可能疏于关心。',
      career: '在公共服务、教育、媒体、政治等社会影响力大的领域大展身手。不惧怕成为焦点，在面对公众的职业中展现自然的魅力。',
      relationship: '在感情中奉献且温暖，但可能对外人比对伴侣更加亲切。因为想要照耀所有人，伴侣可能会产生嫉妒情绪，需要建立在信任基础上的关系。',
      sihua: '化禄通过人气和名声积累财富。化权以强大的领导力引领公共事务。化科获得大众声望和良好口碑。化忌则有过度消耗、倦怠和名誉受损的风险。',
      companion: '与巨门同宫时光与影共存，在争论中揭示真相。与太阴形成对照，阴阳和谐。与天梁同宫则名誉与智慧合一。',
    },
  },
  '武曲': {
    ko: {
      name: '무곡성(武曲星)',
      nickname: '장군의 별',
      element: '금(金)',
      series: '자미 계열',
      overview: '무곡성은 결단력과 재물을 상징하는 별로, 강인한 의지와 실행력을 갖추고 있습니다. 금(金)의 속성답게 날카롭고 단호하며, 특히 재무 분야에서 뛰어난 능력을 발휘합니다.',
      personality: '명궁에 무곡성이 있으면 성격이 강직하고 결단력이 있습니다. 말보다 행동이 앞서며, 목표를 정하면 반드시 달성하려는 의지가 강합니다. 감정 표현이 서툴고 무뚝뚝해 보일 수 있지만, 내면은 의리가 깊고 책임감이 강합니다.',
      career: '금융, 회계, 군인, 엔지니어링 등 정확성과 실행력이 요구되는 분야에서 성공합니다. 재테크 감각이 뛰어나며, 기술 분야에서도 탁월한 능력을 보여줍니다.',
      relationship: '연애에서 로맨틱한 표현보다는 실질적인 행동으로 사랑을 보여줍니다. 진지하고 충직한 파트너이지만, 감정적 교류에 서툴러 상대가 차갑다고 느낄 수 있습니다.',
      sihua: '화록이면 뛰어난 재물 복과 투자 수완을 발휘합니다. 화권이면 군사적 권위와 추진력으로 조직을 이끕니다. 화과면 기술적 명성과 전문가로서의 인정을 받습니다. 화기가 되면 재정적 손실과 금전 문제에 시달립니다.',
      companion: '탐랑(貪狼)과 동궁하면 재물과 욕망이 결합하여 큰 성공 또는 큰 실패를 가져옵니다. 천부(天府)와 함께하면 재정적 안정이 극대화되며, 칠살(七殺)과 만나면 강한 결단력과 행동력을 보입니다.',
    },
    en: {
      name: 'Wu Qu Star (Military Melody)',
      nickname: 'The General Star',
      element: 'Metal',
      series: 'Zi Wei Series',
      overview: 'Wu Qu symbolizes decisiveness and wealth, possessing strong willpower and execution. True to its Metal nature, it is sharp and firm, particularly excelling in financial domains.',
      personality: 'With Wu Qu in the Life Palace, you are upright and decisive. Actions speak louder than words, and you possess strong determination to achieve your goals. Though you may appear blunt and emotionally reserved, you are deeply loyal and responsible inside.',
      career: 'Success comes in fields requiring precision and execution — finance, accounting, military, and engineering. You have excellent financial instincts and demonstrate outstanding abilities in technical fields.',
      relationship: 'In love, you show affection through practical actions rather than romantic gestures. A serious and loyal partner, but your difficulty with emotional communication may make you seem cold.',
      sihua: 'Lu brings exceptional financial fortune and investment acumen. Quan grants military authority and driving force to lead organizations. Ke earns technical reputation and professional recognition. Ji brings financial losses and monetary troubles.',
      companion: 'With Tan Lang, wealth and desire combine for either great success or great failure. With Tian Fu, financial stability is maximized. With Qi Sha, strong decisiveness and action are displayed.',
    },
    ja: {
      name: '武曲星(ぶきょくせい)',
      nickname: '将軍の星',
      element: '金',
      series: '紫微系',
      overview: '武曲星は決断力と財を象徴する星で、強い意志と実行力を備えています。金の属性らしく鋭く断固としており、特に財務分野で優れた能力を発揮します。',
      personality: '命宮に武曲星がある場合、性格が剛直で決断力があります。言葉よりも行動が先立ち、目標を定めたら必ず達成しようとする強い意志を持ちます。感情表現が苦手で無愛想に見えますが、内面は義理堅く責任感が強いです。',
      career: '金融、会計、軍人、エンジニアリングなど正確さと実行力が求められる分野で成功します。資産運用のセンスが優れており、技術分野でも卓越した能力を見せます。',
      relationship: '恋愛ではロマンチックな表現よりも実質的な行動で愛を示します。真面目で忠実なパートナーですが、感情的な交流が苦手なため相手が冷たいと感じることがあります。',
      sihua: '化禄では優れた財運と投資手腕を発揮します。化権では軍事的権威と推進力で組織を導きます。化科では技術的名声と専門家としての認知を得ます。化忌では財政的損失と金銭問題に悩まされます。',
      companion: '貪狼と同宮すると財と欲望が結合し、大成功または大失敗をもたらします。天府と共にあると財政的安定が極大化され、七殺と出会うと強い決断力と行動力を見せます。',
    },
    zh: {
      name: '武曲星',
      nickname: '将军之星',
      element: '金',
      series: '紫微系',
      overview: '武曲星象征决断力与财富，具备强大的意志力和执行力。一如金之属性般锐利果决，尤其在财务领域展现出卓越的能力。',
      personality: '武曲星坐命宫者性格刚正且有决断力。行动优于言语，一旦确定目标就有着必须达成的坚强意志。虽然不善表达情感显得冷硬，但内心重义气、责任感强。',
      career: '在金融、会计、军事、工程等需要精准和执行力的领域中取得成功。具有出色的理财感觉，在技术领域也展现出非凡的能力。',
      relationship: '在感情中以实际行动而非浪漫言辞来表达爱意。是认真且忠诚的伴侣，但因不善于情感交流，可能让对方觉得冷漠。',
      sihua: '化禄时发挥出色的财运和投资才能。化权以军事般的权威和推动力引领组织。化科获得技术声望和专业认可。化忌则饱受财务损失和金钱问题困扰。',
      companion: '与贪狼同宫时财与欲结合，带来大成功或大失败。与天府同宫则财务稳定性达到最大化。与七杀相遇则展现强烈的决断力和行动力。',
    },
  },
  '天同': {
    ko: {
      name: '천동성(天同星)',
      nickname: '복덕의 별',
      element: '수(水)',
      series: '자미 계열',
      overview: '천동성은 복과 안락을 상징하는 별로, 부드럽고 온화한 기운을 품고 있습니다. 예술적 감성이 풍부하며, 편안한 삶과 조화를 추구합니다. 다만 지나친 안일함이 성장의 걸림돌이 될 수 있습니다.',
      personality: '명궁에 천동성이 있으면 온화하고 친근한 성격입니다. 사람들과 잘 어울리며 갈등을 피하려 합니다. 예술적 감수성이 뛰어나고 감성이 풍부하지만, 결정적인 순간에 우유부단하고 안주하려는 경향이 있습니다.',
      career: '예술, 엔터테인먼트, 복지, 서비스업 등 사람을 편안하게 하는 분야에서 활약합니다. 큰 야망보다는 안정적이고 즐거운 직업 환경을 선호하며, 창작 분야에서 재능을 발휘합니다.',
      relationship: '연애에서 따뜻하고 다정한 파트너입니다. 갈등을 싫어해 맞추어 주는 편이지만, 너무 수동적이 되면 관계의 활력이 떨어질 수 있습니다. 평화롭고 안정적인 관계를 지향합니다.',
      sihua: '화록이면 큰 노력 없이도 복이 들어오는 타입입니다. 화권이면 부드러운 리더십으로 조직을 이끕니다. 화과면 예술적 명성을 얻습니다. 화기가 되면 나태함과 안일함에 빠져 기회를 놓칩니다.',
      companion: '태음(太陰)과 동궁하면 감성이 극대화되어 예술 분야에서 빛납니다. 거문(巨門)과 만나면 내면의 갈등이 생기지만 성장의 계기가 됩니다. 천량(天梁)과 함께하면 복과 지혜가 조화를 이룹니다.',
    },
    en: {
      name: 'Tian Tong Star (Heavenly Unity)',
      nickname: 'The Blessing Star',
      element: 'Water',
      series: 'Zi Wei Series',
      overview: 'Tian Tong symbolizes blessings and comfort, carrying gentle and mild energy. Rich in artistic sensibility, it pursues a comfortable life and harmony. However, excessive complacency can hinder growth.',
      personality: 'With Tian Tong in the Life Palace, you have a gentle and approachable personality. You get along well with others and avoid conflict. Your artistic sensitivity is outstanding, but you tend toward indecisiveness and complacency at critical moments.',
      career: 'You thrive in fields that comfort people — arts, entertainment, welfare, and service industries. You prefer stable and enjoyable work environments over grand ambition, and excel in creative fields.',
      relationship: 'A warm and affectionate partner in relationships. You tend to accommodate to avoid conflict, but becoming too passive may drain relationship vitality. You seek peaceful and stable relationships.',
      sihua: 'Lu brings blessings with minimal effort. Quan grants gentle leadership ability. Ke earns artistic fame. Ji leads to laziness and complacency, causing missed opportunities.',
      companion: 'With Tai Yin, emotions are maximized, shining in the arts. With Ju Men, inner conflict arises but serves as a growth catalyst. With Tian Liang, blessings and wisdom harmonize.',
    },
    ja: {
      name: '天同星(てんどうせい)',
      nickname: '福徳の星',
      element: '水',
      series: '紫微系',
      overview: '天同星は福と安楽を象徴する星で、柔らかく穏やかな気を秘めています。芸術的感性が豊かで、快適な暮らしと調和を追求します。ただし、過度な安逸さが成長の妨げとなることがあります。',
      personality: '命宮に天同星がある場合、穏やかで親しみやすい性格です。人と上手く交わり争いを避けようとします。芸術的感受性に優れ感性豊かですが、決定的な場面で優柔不断になりがちで現状に安住する傾向があります。',
      career: '芸術、エンターテインメント、福祉、サービス業など人を心地よくさせる分野で活躍します。大きな野心よりも安定的で楽しい職場環境を好み、創作分野で才能を発揮します。',
      relationship: '恋愛では温かく優しいパートナーです。争いを嫌い合わせがちですが、あまりに受動的になると関係の活力が失われることがあります。穏やかで安定した関係を志向します。',
      sihua: '化禄では大きな努力なくとも福が入ってくるタイプです。化権では穏やかなリーダーシップで組織を導きます。化科では芸術的名声を得ます。化忌では怠惰と安逸に陥り、機会を逃します。',
      companion: '太陰と同宮すると感性が極大化され芸術分野で輝きます。巨門と出会うと内面の葛藤が生じますが成長のきっかけとなります。天梁と共にあると福と知恵が調和します。',
    },
    zh: {
      name: '天同星',
      nickname: '福德之星',
      element: '水',
      series: '紫微系',
      overview: '天同星象征福气与安逸，蕴含柔和温润的气息。艺术感性丰富，追求舒适的生活与和谐。但过度的安逸可能成为成长的障碍。',
      personality: '天同星坐命宫者性格温和亲切。与人相处融洽，倾向于回避冲突。艺术感受力出色且感性丰富，但在关键时刻容易优柔寡断，有安于现状的倾向。',
      career: '在艺术、娱乐、福利、服务业等让人感到舒适的领域中活跃。比起远大抱负，更偏好稳定愉快的工作环境，在创作领域发挥才华。',
      relationship: '在感情中是温暖体贴的伴侣。不喜冲突而倾向于迁就对方，但过于被动可能导致关系失去活力。追求平和稳定的感情关系。',
      sihua: '化禄时不需太多努力就能获得福气。化权以温和的领导力带领团队。化科获得艺术声望。化忌则陷入懒惰和安逸，错失良机。',
      companion: '与太阴同宫时感性达到极致，在艺术领域闪耀。与巨门相遇会产生内心矛盾，但成为成长的契机。与天梁同宫则福气与智慧和谐统一。',
    },
  },
  '廉貞': {
    ko: {
      name: '염정성(廉貞星)',
      nickname: '열정의 별',
      element: '화(火)',
      series: '자미 계열',
      overview: '염정성은 강렬한 감정과 복잡한 매력을 가진 별입니다. 화(火)의 속성으로 열정적이고 카리스마가 넘치지만, 그 에너지가 어디로 향하느냐에 따라 길흉이 크게 갈립니다. 정치력과 예술적 감각이 모두 뛰어납니다.',
      personality: '명궁에 염정성이 있으면 강한 개성과 매력을 지닙니다. 감정의 기복이 크고 열정적이어서 사람들을 끌어들이는 매력이 있습니다. 복잡한 내면 세계를 가지고 있으며, 사랑과 미움이 분명합니다.',
      career: '정치, 법률, 예술, 연예 등 복합적인 능력이 필요한 분야에서 두각을 나타냅니다. 위험을 무릅쓰는 대담함이 있어 도전적인 업무를 즐기며, 창작과 기획 모두에서 역량을 발휘합니다.',
      relationship: '연애에서 매우 열정적이고 깊은 감정을 느낍니다. 사랑에 올인하는 타입으로, 강렬한 연애를 하지만 집착이나 감정 폭발로 이어질 수 있습니다. 복잡한 연애사를 겪기 쉽습니다.',
      sihua: '화록이면 열정이 성공으로 연결되어 사업이나 정치에서 크게 이름을 떨칩니다. 화권이면 정치적 수완과 권모술수에 능합니다. 화과면 예술적 재능으로 명성을 얻습니다. 화기가 되면 법적 문제나 감정적 분쟁에 휘말립니다.',
      companion: '탐랑(貪狼)과 동궁하면 도화(桃花)가 강해져 매력이 넘치지만 감정 문제가 복잡해집니다. 천부(天府)와 만나면 열정에 안정감이 더해지며, 칠살(七殺)과 함께하면 강한 추진력을 보입니다.',
    },
    en: {
      name: 'Lian Zhen Star (Purity)',
      nickname: 'The Passion Star',
      element: 'Fire',
      series: 'Zi Wei Series',
      overview: 'Lian Zhen carries intense emotions and complex charm. With Fire nature, it is passionate and charismatic, but fortune varies greatly depending on where that energy is directed. Both political acumen and artistic sensibility are exceptional.',
      personality: 'With Lian Zhen in the Life Palace, you have a strong personality and magnetic charm. With emotional highs and lows, your passion draws people in. You have a complex inner world with clear distinctions between love and hate.',
      career: 'You excel in fields requiring multifaceted abilities — politics, law, arts, and entertainment. Your boldness in taking risks means you enjoy challenging work, demonstrating capability in both creation and planning.',
      relationship: 'Extremely passionate in love with deep emotional intensity. You go all-in on romance, experiencing intense relationships that may lead to obsession or emotional outbursts. Complex relationship histories are common.',
      sihua: 'Lu connects passion to success, making a big name in business or politics. Quan excels at political maneuvering. Ke earns fame through artistic talent. Ji leads to legal troubles or emotional disputes.',
      companion: 'With Tan Lang, romance energy intensifies — charm overflows but emotional complications arise. With Tian Fu, stability tempers passion. With Qi Sha, strong driving force emerges.',
    },
    ja: {
      name: '廉貞星(れんていせい)',
      nickname: '情熱の星',
      element: '火',
      series: '紫微系',
      overview: '廉貞星は強烈な感情と複雑な魅力を持つ星です。火の属性で情熱的でカリスマに溢れていますが、そのエネルギーの向かう先により吉凶が大きく分かれます。政治力と芸術的感覚の両方に優れています。',
      personality: '命宮に廉貞星がある場合、強い個性と魅力を持ちます。感情の起伏が大きく情熱的で、人を引きつける魅力があります。複雑な内面世界を持ち、好き嫌いがはっきりしています。',
      career: '政治、法律、芸術、芸能など複合的な能力が必要な分野で頭角を現します。危険を冒す大胆さがあり挑戦的な業務を楽しみ、創作と企画の両方で力を発揮します。',
      relationship: '恋愛では非常に情熱的で深い感情を感じます。恋に全力を注ぐタイプで、激しい恋愛をしますが執着や感情の爆発につながることがあります。複雑な恋愛遍歴を経験しやすいです。',
      sihua: '化禄では情熱が成功に結びつき、事業や政治で大きく名を馳せます。化権では政治的手腕と権謀術策に長けます。化科では芸術的才能で名声を得ます。化忌では法的問題や感情的紛争に巻き込まれます。',
      companion: '貪狼と同宮すると桃花が強まり魅力が溢れますが感情問題が複雑化します。天府と出会うと情熱に安定感が加わり、七殺と共にあると強い推進力を見せます。',
    },
    zh: {
      name: '廉贞星',
      nickname: '热情之星',
      element: '火',
      series: '紫微系',
      overview: '廉贞星拥有强烈的情感和复杂的魅力。火之属性使其充满激情和领袖气质，但根据能量的指向不同，吉凶差异极大。政治能力和艺术感觉皆为出色。',
      personality: '廉贞星坐命宫者具有强烈的个性和吸引力。情绪起伏大且充满激情，有着吸引众人的魅力。内心世界复杂，爱恨分明。',
      career: '在政治、法律、艺术、演艺等需要综合能力的领域中脱颖而出。有冒险的胆识，享受挑战性的工作，在创作和策划方面均能展现实力。',
      relationship: '在感情中极为热烈，能感受到深厚的情感。属于全身心投入恋爱的类型，恋爱激烈但可能走向执念或情绪失控。容易经历复杂的感情经历。',
      sihua: '化禄时热情与成功相连，在事业或政治上大放异彩。化权擅长政治手腕和权谋策略。化科以艺术才华获得声望。化忌则卷入法律纠纷或情感冲突。',
      companion: '与贪狼同宫时桃花运增强，魅力四溢但情感问题变得复杂。与天府相遇则热情中添加稳定。与七杀同宫则展现强大的推进力。',
    },
  },
  '天府': {
    ko: {
      name: '천부성(天府星)',
      nickname: '재고의 별',
      element: '토(土)',
      series: '천부 계열',
      overview: '천부성은 안정과 재물 관리를 상징하는 별로, 천부 계열의 수장입니다. 토(土)의 든든한 속성처럼 신뢰성과 포용력이 뛰어나며, 재산을 지키고 불려나가는 능력이 탁월합니다.',
      personality: '명궁에 천부성이 있으면 침착하고 신중한 성격을 지닙니다. 안정을 추구하며 계획적으로 일을 처리합니다. 관대하고 포용력이 있어 사람들의 신뢰를 받지만, 보수적이고 변화를 꺼리는 면이 있습니다.',
      career: '재무관리, 은행, 부동산, 대기업 관리직 등 안정적이고 체계적인 분야에서 성공합니다. 조직을 안정적으로 운영하는 능력이 탁월하며, 자산 관리와 재테크에도 뛰어난 감각을 보입니다.',
      relationship: '연애에서 믿음직하고 안정적인 파트너입니다. 화려한 연애보다는 꾸준하고 성실한 관계를 추구하며, 가정을 잘 꾸려나가는 타입입니다. 상대에게 경제적 안정감을 줍니다.',
      sihua: '화록이면 꾸준하고 안정적인 재물 축적이 이루어집니다. 화권이면 조직 관리와 통솔에 탁월한 능력을 발휘합니다. 화과면 신뢰할 수 있는 인물로 명성을 얻습니다. 화기가 되면 재정에 대한 불안과 걱정이 끊이지 않습니다.',
      companion: '자미(紫微)와 동궁하면 재왕합벽으로 최고의 격을 이룹니다. 염정(廉貞)과 만나면 열정에 안정감이 더해지고, 무곡(武曲)과 함께하면 재물 운이 더욱 강해집니다.',
    },
    en: {
      name: 'Tian Fu Star (Heavenly Treasury)',
      nickname: 'The Treasury Star',
      element: 'Earth',
      series: 'Tian Fu Series',
      overview: 'Tian Fu symbolizes stability and wealth management, leading the Tian Fu series. Like the Earth element\'s reliable nature, it excels in trustworthiness and inclusiveness, with outstanding ability to preserve and grow assets.',
      personality: 'With Tian Fu in the Life Palace, you are calm and prudent. You seek stability and handle matters methodically. Generous and inclusive, you earn people\'s trust, though you can be conservative and resistant to change.',
      career: 'Success comes in stable and systematic fields — financial management, banking, real estate, and corporate management. You excel at running organizations smoothly, with keen financial and investment instincts.',
      relationship: 'A reliable and stable partner in relationships. You pursue steady and faithful relationships over flashy romances, and you excel at building a household. You provide financial security to your partner.',
      sihua: 'Lu brings steady and stable wealth accumulation. Quan excels at organizational management and leadership. Ke earns reputation as a trustworthy figure. Ji brings persistent financial anxiety and worry.',
      companion: 'With Zi Wei, it forms the Emperor-Treasury pairing — the highest format. With Lian Zhen, stability tempers passion. With Wu Qu, wealth fortune strengthens further.',
    },
    ja: {
      name: '天府星(てんぷせい)',
      nickname: '財庫の星',
      element: '土',
      series: '天府系',
      overview: '天府星は安定と財の管理を象徴する星で、天府系の長です。土の頼もしい属性のように信頼性と包容力に優れ、財産を守り増やす能力が卓越しています。',
      personality: '命宮に天府星がある場合、沈着で慎重な性格を持ちます。安定を追求し計画的に物事を処理します。寛大で包容力があり人々の信頼を得ますが、保守的で変化を嫌う面があります。',
      career: '財務管理、銀行、不動産、大企業管理職など安定的で体系的な分野で成功します。組織を安定的に運営する能力が卓越し、資産管理と投資にも優れたセンスを見せます。',
      relationship: '恋愛では頼りがいのある安定的なパートナーです。華やかな恋愛よりも着実で誠実な関係を追求し、家庭をしっかり築いていくタイプです。相手に経済的な安心感を与えます。',
      sihua: '化禄では着実で安定した財の蓄積が実現します。化権では組織管理と統率に卓越した能力を発揮します。化科では信頼できる人物として名声を得ます。化忌では財政に対する不安と心配が絶えません。',
      companion: '紫微と同宮すると帝王合璧で最高の格を成します。廉貞と出会うと情熱に安定感が加わり、武曲と共にあると財運がさらに強くなります。',
    },
    zh: {
      name: '天府星',
      nickname: '财库之星',
      element: '土',
      series: '天府系',
      overview: '天府星象征稳定与财富管理，是天府系的首领。如同土之属性般可靠，信誉度和包容力出众，守护和增长资产的能力卓越。',
      personality: '天府星坐命宫者性格沉稳谨慎。追求稳定，做事有条不紊。宽厚包容，深得他人信赖，但有保守、不愿变化的一面。',
      career: '在财务管理、银行、房地产、大企业管理等稳定系统的领域中取得成功。稳定运营组织的能力卓越，在资产管理和理财方面也展现出色的感觉。',
      relationship: '在感情中是值得信赖且稳定的伴侣。比起轰轰烈烈的恋爱，更追求稳定真诚的关系，善于经营家庭。能给予对方经济上的安全感。',
      sihua: '化禄时实现稳健持续的财富积累。化权在组织管理和统领方面发挥卓越能力。化科以值得信赖的形象赢得声望。化忌则对财务的焦虑和担忧不断。',
      companion: '与紫微同宫称为帝王合璧，达到最高格局。与廉贞相遇则热情中增添稳定。与武曲同宫则财运更为强劲。',
    },
  },
  '太陰': {
    ko: {
      name: '태음성(太陰星)',
      nickname: '달의 별',
      element: '수(水)',
      series: '천부 계열',
      overview: '태음성은 달을 상징하는 별로, 섬세한 감성과 풍부한 직관력을 나타냅니다. 부동산과 재산 축적에 유리하며, 아름다움과 예술에 대한 감각이 뛰어납니다. 밤에 태어난 사람에게 더 유리한 별입니다.',
      personality: '명궁에 태음성이 있으면 감수성이 풍부하고 직관력이 뛰어납니다. 섬세하고 조용한 성격으로, 내면이 풍부합니다. 예술적 감각이 있으며, 아름다운 것을 추구합니다. 다만 감정적으로 불안정해지기 쉽고, 걱정이 많은 편입니다.',
      career: '부동산, 인테리어, 패션, 미용 등 아름다움과 관련된 분야에서 성공합니다. 부동산 투자 감각이 뛰어나며, 문학이나 예술 분야에서도 재능을 발휘합니다.',
      relationship: '연애에서 로맨틱하고 섬세한 감정을 중시합니다. 분위기와 감성을 중요하게 여기며, 깊은 정서적 유대를 원합니다. 상대의 감정 변화에 민감하여 불안을 느끼기 쉽습니다.',
      sihua: '화록이면 부동산이나 자산을 통한 재물 축적이 유리합니다. 화권이면 조용하지만 확실한 권위를 발휘합니다. 화과면 예술적 명성과 아름다운 이미지를 얻습니다. 화기가 되면 감정 불안정과 우울감에 시달립니다.',
      companion: '천기(天機)와 동궁하면 감성과 지성이 조화를 이룹니다. 천동(天同)과 만나면 감성이 극대화되고, 태양(太陽)과는 음양의 대비를 이루어 균형잡힌 에너지를 나타냅니다.',
    },
    en: {
      name: 'Tai Yin Star (The Moon)',
      nickname: 'The Moon Star',
      element: 'Water',
      series: 'Tian Fu Series',
      overview: 'Tai Yin represents the moon, embodying delicate sensibility and rich intuition. Favorable for real estate and asset accumulation, with outstanding aesthetic and artistic sense. More auspicious for those born at night.',
      personality: 'With Tai Yin in the Life Palace, you are deeply sensitive and intuitive. Gentle and quiet, you have a rich inner world. You possess artistic sense and pursue beauty. However, you can be emotionally unstable and prone to worry.',
      career: 'Success in beauty-related fields — real estate, interior design, fashion, and aesthetics. You have excellent real estate investment instincts and talent in literature and arts.',
      relationship: 'You value romantic and delicate emotions in love. Atmosphere and sentiment matter greatly, and you desire deep emotional bonds. Your sensitivity to partner\'s emotional changes can trigger anxiety.',
      sihua: 'Lu favors asset accumulation through real estate. Quan brings quiet but definitive authority. Ke earns artistic fame and a beautiful image. Ji leads to emotional instability and melancholy.',
      companion: 'With Tian Ji, sensibility and intellect harmonize. With Tian Tong, emotions are maximized. With Tai Yang, yin-yang contrast creates balanced energy.',
    },
    ja: {
      name: '太陰星(たいいんせい)',
      nickname: '月の星',
      element: '水',
      series: '天府系',
      overview: '太陰星は月を象徴する星で、繊細な感性と豊かな直観力を表します。不動産や財産の蓄積に有利で、美しさと芸術に対するセンスが優れています。夜生まれの人により有利な星です。',
      personality: '命宮に太陰星がある場合、感受性が豊かで直観力に優れています。繊細で静かな性格で、内面が豊かです。芸術的感覚があり美しいものを追求します。ただし感情的に不安定になりやすく、心配性な面があります。',
      career: '不動産、インテリア、ファッション、美容など美に関連する分野で成功します。不動産投資のセンスが優れており、文学や芸術分野でも才能を発揮します。',
      relationship: '恋愛ではロマンチックで繊細な感情を重視します。雰囲気と感性を大切にし、深い情緒的絆を求めます。相手の感情変化に敏感で不安を感じやすいです。',
      sihua: '化禄では不動産や資産を通じた財の蓄積が有利です。化権では静かだが確かな権威を発揮します。化科では芸術的名声と美しいイメージを得ます。化忌では感情の不安定さと憂鬱に悩まされます。',
      companion: '天機と同宮すると感性と知性が調和します。天同と出会うと感性が極大化され、太陽とは陰陽の対比を成しバランスの取れたエネルギーを表します。',
    },
    zh: {
      name: '太阴星',
      nickname: '月亮之星',
      element: '水',
      series: '天府系',
      overview: '太阴星象征月亮，体现细腻的感性和丰富的直觉力。有利于房地产和资产积累，对美和艺术有出色的感觉。对于夜晚出生的人更为有利。',
      personality: '太阴星坐命宫者感受性丰富且直觉力出众。性格细腻安静，内心世界丰富。具有艺术感觉，追求美好事物。但容易情绪不稳定，比较多愁善感。',
      career: '在房地产、室内设计、时尚、美容等与美相关的领域取得成功。房地产投资感觉敏锐，在文学和艺术领域也能展现才华。',
      relationship: '在感情中重视浪漫和细腻的情感。看重氛围和感性，渴望深层的情感纽带。对伴侣的情绪变化敏感，容易感到不安。',
      sihua: '化禄时有利于通过房地产或资产实现财富积累。化权发挥安静但确定的权威。化科获得艺术声望和美好形象。化忌则饱受情绪不稳和忧郁之苦。',
      companion: '与天机同宫时感性与理性和谐统一。与天同相遇则感性达到极致。与太阳形成阴阳对比，呈现平衡的能量。',
    },
  },
  '貪狼': {
    ko: {
      name: '탐랑성(貪狼星)',
      nickname: '욕망의 별',
      element: '목수(木水)',
      series: '천부 계열',
      overview: '탐랑성은 다재다능함과 강한 욕구를 상징하는 별입니다. 목(木)과 수(水)의 이중 속성을 지니며, 변화무쌍하고 매력적입니다. 도화성(桃花星)의 성격도 겸하여 이성에 대한 매력이 뛰어납니다.',
      personality: '명궁에 탐랑성이 있으면 다재다능하고 사교적인 성격입니다. 호기심이 왕성하고 다양한 분야에 관심을 보이며, 인생을 즐기려는 성향이 강합니다. 매력적이고 변화를 즐기지만, 욕심이 과하면 집중력이 흐트러질 수 있습니다.',
      career: '연예, 영업, 요식업, 유흥업 등 사람과 소통하는 분야에서 성공합니다. 다양한 재능을 살릴 수 있는 직업이 적합하며, 한 분야에만 국한되지 않는 복합적인 경력을 쌓는 경우가 많습니다.',
      relationship: '이성에게 매력적이며 연애 경험이 풍부한 편입니다. 로맨틱하고 재미있는 파트너이지만, 한 사람에게 집중하기 어려울 수 있으며, 유혹에 약한 면이 있습니다.',
      sihua: '화록이면 다양한 수입원을 통해 재물을 모읍니다. 화권이면 사회적 영향력과 인맥으로 권력을 얻습니다. 화과면 다방면의 재능으로 명성을 떨칩니다. 화기가 되면 중독이나 집착에 빠지기 쉽습니다.',
      companion: '무곡(武曲)과 동궁하면 재물과 욕망이 결합하여 큰 성취를 이룹니다. 염정(廉貞)과 만나면 매력이 극대화되지만 감정적 복잡함이 증가하며, 자미(紫微)와 함께하면 욕망에 품격이 더해집니다.',
    },
    en: {
      name: 'Tan Lang Star (Greedy Wolf)',
      nickname: 'The Desire Star',
      element: 'Wood-Water',
      series: 'Tian Fu Series',
      overview: 'Tan Lang symbolizes versatility and strong desires. Possessing dual Wood-Water attributes, it is ever-changing and charming. Also carrying Peach Blossom star qualities, it grants exceptional romantic appeal.',
      personality: 'With Tan Lang in the Life Palace, you are versatile and sociable. Curious and interested in diverse fields, you have a strong drive to enjoy life. Charming and change-loving, but excess desire may scatter your focus.',
      career: 'Success in people-oriented fields — entertainment, sales, food service, and hospitality. Careers utilizing diverse talents suit you best; you often build multi-faceted career paths.',
      relationship: 'Attractive to the opposite sex with rich romantic experience. A romantic and fun partner, but you may struggle focusing on one person and can be susceptible to temptation.',
      sihua: 'Lu brings wealth through diverse income streams. Quan gains power through social influence and connections. Ke earns fame through multifaceted talent. Ji risks addiction or obsession.',
      companion: 'With Wu Qu, wealth and desire combine for great achievement. With Lian Zhen, charm is maximized but emotional complexity increases. With Zi Wei, dignity is added to desire.',
    },
    ja: {
      name: '貪狼星(たんろうせい)',
      nickname: '欲望の星',
      element: '木水',
      series: '天府系',
      overview: '貪狼星は多才多芸と強い欲求を象徴する星です。木と水の二重属性を持ち、変幻自在で魅力的です。桃花星の性格も兼ね備え、異性への魅力が非常に優れています。',
      personality: '命宮に貪狼星がある場合、多才で社交的な性格です。好奇心が旺盛で多様な分野に関心を示し、人生を楽しもうとする性向が強いです。魅力的で変化を楽しみますが、欲が過ぎると集中力が散漫になることがあります。',
      career: '芸能、営業、飲食業、接客業など人とコミュニケーションする分野で成功します。多様な才能を活かせる職業が適しており、一つの分野に限定されない複合的なキャリアを築くことが多いです。',
      relationship: '異性に魅力的で恋愛経験が豊富な方です。ロマンチックで楽しいパートナーですが、一人に集中するのが難しく、誘惑に弱い面があります。',
      sihua: '化禄では多様な収入源を通じて財を集めます。化権では社会的影響力と人脈で権力を得ます。化科では多方面の才能で名声を馳せます。化忌では中毒や執着に陥りやすくなります。',
      companion: '武曲と同宮すると財と欲望が結合し大きな成果を上げます。廉貞と出会うと魅力が極大化されますが感情的複雑さが増します。紫微と共にあると欲望に品格が加わります。',
    },
    zh: {
      name: '贪狼星',
      nickname: '欲望之星',
      element: '木水',
      series: '天府系',
      overview: '贪狼星象征多才多艺和强烈的欲望。兼具木与水的双重属性，变幻莫测且魅力十足。同时具有桃花星的特质，对异性有着非凡的吸引力。',
      personality: '贪狼星坐命宫者多才多艺且善于社交。好奇心旺盛，对各个领域都感兴趣，有着强烈的享受人生的倾向。富有魅力且喜欢变化，但欲望过度时可能导致注意力分散。',
      career: '在演艺、销售、餐饮、服务业等与人交流的领域取得成功。适合能发挥多种才能的职业，往往构建跨领域的复合型职业生涯。',
      relationship: '对异性有吸引力，恋爱经验丰富。是浪漫有趣的伴侣，但可能难以专注于一个人，面对诱惑时容易动摇。',
      sihua: '化禄通过多元收入来源积聚财富。化权凭借社会影响力和人脉获得权力。化科以多方面的才华赢得声誉。化忌则容易陷入上瘾或执念。',
      companion: '与武曲同宫时财与欲结合达成大成就。与廉贞相遇魅力达到极致但情感复杂度增加。与紫微同宫则欲望中添加品格。',
    },
  },
  '巨門': {
    ko: {
      name: '거문성(巨門星)',
      nickname: '어둠의 별',
      element: '수(水)',
      series: '천부 계열',
      overview: '거문성은 언변과 분석력을 상징하는 별로, 사물의 본질을 꿰뚫어 보는 날카로운 통찰력을 지닙니다. 암성(暗星)이라고도 불리며, 진실을 파헤치는 능력이 뛰어나지만 그로 인한 시비구설이 따르기도 합니다.',
      personality: '명궁에 거문성이 있으면 언변이 뛰어나고 분석적입니다. 사물의 이면을 보는 능력이 있어 비판적 사고에 능합니다. 논리정연하고 설득력이 있지만, 의심이 많고 남을 쉽게 믿지 못하는 경향이 있습니다.',
      career: '법률, 언론, 교육, 연구 등 말과 글을 다루는 직업에서 두각을 나타냅니다. 토론과 논쟁에 강하며, 진실을 밝히는 직업(탐사보도, 수사)에도 적합합니다.',
      relationship: '연애에서 솔직하고 직설적인 의사소통을 합니다. 상대의 거짓을 쉽게 간파하며, 진실한 관계를 원합니다. 다만 지나친 의심과 말다툼으로 관계가 힘들어질 수 있습니다.',
      sihua: '화록이면 뛰어난 언변으로 재물을 모읍니다. 화권이면 토론과 논쟁에서 압도적인 힘을 발휘합니다. 화과면 학문적 명성과 교육자로서의 인정을 받습니다. 화기가 되면 구설수와 비방에 시달립니다.',
      companion: '태양(太陽)과 동궁하면 빛과 그림자의 조화로 진실을 밝히는 힘이 강해집니다. 천기(天機)와 만나면 분석력이 극대화되며, 천동(天同)과 함께하면 내면의 갈등과 성장이 공존합니다.',
    },
    en: {
      name: 'Ju Men Star (Giant Gate)',
      nickname: 'The Dark Star',
      element: 'Water',
      series: 'Tian Fu Series',
      overview: 'Ju Men symbolizes eloquence and analytical power, possessing sharp insight into the nature of things. Also called the Dark Star, it excels at uncovering truth, though this may invite gossip and controversy.',
      personality: 'With Ju Men in the Life Palace, you are eloquent and analytical. You can see behind surface appearances, skilled in critical thinking. Logical and persuasive, but tend to be suspicious and slow to trust others.',
      career: 'You stand out in careers involving words and writing — law, media, education, and research. Strong in debate and argumentation, also suited for truth-revealing work (investigative journalism, criminal investigation).',
      relationship: 'Honest and direct in romantic communication. You easily see through partner\'s deceptions and want genuine relationships. However, excessive suspicion and arguments may strain relationships.',
      sihua: 'Lu brings wealth through exceptional eloquence. Quan grants overwhelming power in debates. Ke earns academic fame and recognition as an educator. Ji leads to gossip and slander.',
      companion: 'With Tai Yang, light-shadow harmony strengthens truth-revealing power. With Tian Ji, analytical ability is maximized. With Tian Tong, inner conflict and growth coexist.',
    },
    ja: {
      name: '巨門星(こもんせい)',
      nickname: '暗の星',
      element: '水',
      series: '天府系',
      overview: '巨門星は弁舌と分析力を象徴する星で、物事の本質を見抜く鋭い洞察力を持ちます。暗星とも呼ばれ、真実を暴く能力に優れていますが、それに伴う是非や口舌が付きまとうこともあります。',
      personality: '命宮に巨門星がある場合、弁舌に優れ分析的です。物事の裏を見る能力があり批判的思考に長けています。論理整然で説得力がありますが、疑り深く人を簡単に信じない傾向があります。',
      career: '法律、報道、教育、研究など言葉と文章を扱う職業で頭角を現します。討論と論争に強く、真実を明らかにする職業（調査報道、捜査）にも適しています。',
      relationship: '恋愛では率直で直接的なコミュニケーションをします。相手の嘘を簡単に見抜き、真実の関係を求めます。ただし、過度な疑いと口論で関係が困難になることがあります。',
      sihua: '化禄では優れた弁舌で財を集めます。化権では討論と論争で圧倒的な力を発揮します。化科では学問的名声と教育者としての認知を得ます。化忌では口舌の災いと誹謗に悩まされます。',
      companion: '太陽と同宮すると光と影の調和で真実を明らかにする力が強まります。天機と出会うと分析力が極大化されます。天同と共にあると内面の葛藤と成長が共存します。',
    },
    zh: {
      name: '巨门星',
      nickname: '暗曜之星',
      element: '水',
      series: '天府系',
      overview: '巨门星象征口才与分析力，拥有洞察事物本质的敏锐目光。又称暗星，揭示真相的能力出众，但也因此可能招致是非口舌。',
      personality: '巨门星坐命宫者口才出众且善于分析。能看透事物背后的真相，擅长批判性思维。逻辑清晰且有说服力，但多疑且不轻易相信他人。',
      career: '在法律、媒体、教育、研究等与言语文字相关的职业中脱颖而出。善于辩论和争论，也适合揭示真相的工作（调查报道、侦查）。',
      relationship: '在感情中坦率直接地沟通。容易识破对方的谎言，渴望真实的关系。但过度的猜疑和争吵可能使关系变得困难。',
      sihua: '化禄以出色的口才积聚财富。化权在辩论争论中展现压倒性的力量。化科获得学术声望和作为教育者的认可。化忌则饱受流言蜚语和诽谤之苦。',
      companion: '与太阳同宫时光影和谐，揭示真相的力量增强。与天机相遇则分析能力达到极致。与天同同宫则内心矛盾与成长并存。',
    },
  },
  '天相': {
    ko: {
      name: '천상성(天相星)',
      nickname: '재상의 별',
      element: '수(水)',
      series: '천부 계열',
      overview: '천상성은 외교와 봉사를 상징하는 별로, 조화와 균형을 추구합니다. 재상(宰相)처럼 뒤에서 조직을 보좌하며 실질적인 역할을 수행하는 능력이 뛰어납니다. 미적 감각과 사회성이 동시에 뛰어난 별입니다.',
      personality: '명궁에 천상성이 있으면 균형 잡힌 성격과 뛰어난 사회성을 지닙니다. 사람들 사이에서 중재 역할을 잘하며, 세련된 매너와 깔끔한 외모를 중시합니다. 남을 돕는 것을 좋아하지만, 너무 남의 눈치를 보며 자기 주장을 못하는 경우가 있습니다.',
      career: '비서직, 외교관, 인사관리, 패션, 디자인 등 사람과 조직을 연결하는 역할에서 성공합니다. 조직의 핵심 참모로 활약하며, 미적 감각을 살린 직업에서도 두각을 나타냅니다.',
      relationship: '연애에서 배려심 깊고 세심한 파트너입니다. 상대의 필요를 잘 파악하고 맞추어 주지만, 자신의 감정을 억누르는 경향이 있어 내면의 불만이 쌓일 수 있습니다.',
      sihua: '화록이면 대인 관계를 통해 안정적인 재물을 모읍니다. 화권이면 외교적 수완으로 실질적인 권력을 행사합니다. 화과면 사회적 명성과 좋은 평판을 얻습니다. 화기가 되면 과도한 눈치 보기와 자기 희생으로 지칩니다.',
      companion: '자미(紫微)와 동궁하면 현명한 보좌로 제왕을 돕는 최상의 조합입니다. 염정(廉貞)의 열정에 균형을 제공하며, 무곡(武曲)과 함께하면 실무적 능력이 강화됩니다.',
    },
    en: {
      name: 'Tian Xiang Star (Heavenly Minister)',
      nickname: 'The Minister Star',
      element: 'Water',
      series: 'Tian Fu Series',
      overview: 'Tian Xiang symbolizes diplomacy and service, pursuing harmony and balance. Like a prime minister supporting from behind, it excels at fulfilling substantial roles. Outstanding in both aesthetic sense and sociability.',
      personality: 'With Tian Xiang in the Life Palace, you have a balanced personality and excellent social skills. You mediate well among people, valuing refined manners and neat appearance. You enjoy helping others but may prioritize others\' opinions over your own assertions.',
      career: 'Success in roles connecting people and organizations — secretarial work, diplomacy, HR management, fashion, and design. You serve as a core advisor in organizations and stand out in aesthetically-oriented careers.',
      relationship: 'A considerate and attentive partner in love. You understand and accommodate your partner\'s needs well, but tend to suppress your own emotions, which may build internal resentment.',
      sihua: 'Lu brings stable wealth through interpersonal relationships. Quan exercises practical power through diplomatic skill. Ke earns social reputation and good standing. Ji leads to exhaustion from excessive people-pleasing and self-sacrifice.',
      companion: 'With Zi Wei, it forms the ideal combination — wise counsel supporting the emperor. It provides balance to Lian Zhen\'s passion, and with Wu Qu, practical abilities are strengthened.',
    },
    ja: {
      name: '天相星(てんそうせい)',
      nickname: '宰相の星',
      element: '水',
      series: '天府系',
      overview: '天相星は外交と奉仕を象徴する星で、調和とバランスを追求します。宰相のように裏で組織を補佐し実質的な役割を果たす能力に優れています。美的感覚と社会性の両方に秀でた星です。',
      personality: '命宮に天相星がある場合、バランスの取れた性格と優れた社交性を持ちます。人々の間で仲裁役をよくこなし、洗練されたマナーと清潔な外見を重視します。人助けが好きですが、周囲の目を気にしすぎて自己主張ができないことがあります。',
      career: '秘書、外交官、人事管理、ファッション、デザインなど人と組織をつなぐ役割で成功します。組織の核心的な参謀として活躍し、美的感覚を活かした職業でも頭角を現します。',
      relationship: '恋愛では思いやりがあり細やかなパートナーです。相手のニーズをよく把握し合わせますが、自分の感情を抑える傾向があり、内面の不満が溜まることがあります。',
      sihua: '化禄では対人関係を通じて安定した財を集めます。化権では外交的手腕で実質的な権力を行使します。化科では社会的名声と良い評判を得ます。化忌では過度な気遣いと自己犠牲で疲れ切ります。',
      companion: '紫微と同宮すると賢明な補佐で帝王を助ける最上の組み合わせです。廉貞の情熱にバランスを提供し、武曲と共にあると実務的能力が強化されます。',
    },
    zh: {
      name: '天相星',
      nickname: '宰相之星',
      element: '水',
      series: '天府系',
      overview: '天相星象征外交与服务，追求和谐与平衡。如宰相般在幕后辅佐组织，发挥实质性作用的能力出众。兼具美感和社交能力。',
      personality: '天相星坐命宫者性格均衡且社交能力出色。善于在人群中担任调解角色，重视优雅的举止和整洁的外表。乐于助人，但有时过于在意他人看法而无法坚持自我主张。',
      career: '在秘书、外交官、人事管理、时尚、设计等连接人与组织的角色中取得成功。作为组织的核心幕僚活跃，在发挥审美感觉的职业中也脱颖而出。',
      relationship: '在感情中是体贴细心的伴侣。善于了解和迎合对方的需求，但倾向于压抑自己的情感，内心的不满可能逐渐累积。',
      sihua: '化禄通过人际关系积聚稳定的财富。化权以外交手腕行使实质性的权力。化科获得社会声望和良好口碑。化忌则因过度迎合他人和自我牺牲而疲惫不堪。',
      companion: '与紫微同宫是贤明辅佐帝王的最佳组合。为廉贞的热情提供平衡。与武曲同宫则实务能力得到强化。',
    },
  },
  '天梁': {
    ko: {
      name: '천량성(天梁星)',
      nickname: '어른의 별',
      element: '토(土)',
      series: '천부 계열',
      overview: '천량성은 지혜와 보호를 상징하는 별로, 원숙하고 도덕적인 품성을 나타냅니다. 어른처럼 남을 보살피고 가르치는 능력이 있으며, 어려운 상황에서도 흔들리지 않는 정신적 강인함을 지닙니다.',
      personality: '명궁에 천량성이 있으면 어른스럽고 책임감이 강합니다. 타인을 보살피는 것을 자연스럽게 여기며, 도덕적 판단력이 뛰어납니다. 다만 지나치게 원칙을 고수하여 융통성이 부족할 수 있으며, 잔소리가 많다는 소리를 듣기도 합니다.',
      career: '교육, 의료, 종교, 공무원 등 사회적 보호와 봉사가 필요한 분야에서 활약합니다. 멘토나 상담사 역할에 적합하며, 전통적인 학문이나 연구에서도 성과를 냅니다.',
      relationship: '연애에서 보호자적인 역할을 합니다. 연인을 돌보고 이끌어 주려 하며, 안정적이고 성숙한 관계를 추구합니다. 다만 상대가 답답함을 느낄 수 있으며, 동등한 파트너보다 부모 같은 역할을 하게 될 수 있습니다.',
      sihua: '화록이면 어른의 덕으로 재물과 복이 따릅니다. 화권이면 도덕적 권위와 교육적 영향력을 발휘합니다. 화과면 학자로서의 명성을 얻습니다. 화기가 되면 완고함과 고집으로 인간관계가 경직됩니다.',
      companion: '천기(天機)와 동궁하면 지혜에 원숙함이 더해져 뛰어난 참모가 됩니다. 태양(太陽)과 만나면 명예와 지혜가 결합하고, 천동(天同)과 함께하면 복과 지혜의 조화가 이루어집니다.',
    },
    en: {
      name: 'Tian Liang Star (Heavenly Beam)',
      nickname: 'The Elder Star',
      element: 'Earth',
      series: 'Tian Fu Series',
      overview: 'Tian Liang symbolizes wisdom and protection, representing mature and moral character. With the ability to care for and teach others like an elder, it possesses mental fortitude that remains unshaken in difficult situations.',
      personality: 'With Tian Liang in the Life Palace, you are mature and highly responsible. You naturally care for others, with excellent moral judgment. However, you may lack flexibility from being too principled, and may be perceived as naggy.',
      career: 'You thrive in fields requiring social protection and service — education, medicine, religion, and civil service. Suited for mentoring and counseling roles, you also achieve results in traditional academics and research.',
      relationship: 'You take on a protective role in relationships. You want to care for and guide your partner, pursuing stable and mature relationships. However, partners may feel stifled, as you may slip into a parental rather than equal partner role.',
      sihua: 'Lu brings wealth and blessings through elder virtue. Quan exercises moral authority and educational influence. Ke earns scholarly fame. Ji leads to rigid relationships due to stubbornness.',
      companion: 'With Tian Ji, maturity enhances wisdom, creating an excellent advisor. With Tai Yang, honor and wisdom combine. With Tian Tong, blessings and wisdom harmonize.',
    },
    ja: {
      name: '天梁星(てんりょうせい)',
      nickname: '長老の星',
      element: '土',
      series: '天府系',
      overview: '天梁星は知恵と保護を象徴する星で、円熟した道徳的な品性を表します。長老のように他者を見守り教える能力があり、困難な状況でも揺るがない精神的強さを持ちます。',
      personality: '命宮に天梁星がある場合、大人びていて責任感が強いです。他者を見守ることを自然に行い、道徳的判断力に優れています。ただし、原則に固執しすぎて融通が利かないことがあり、小言が多いと言われることもあります。',
      career: '教育、医療、宗教、公務員など社会的保護と奉仕が必要な分野で活躍します。メンターやカウンセラーの役割に適しており、伝統的な学問や研究でも成果を上げます。',
      relationship: '恋愛では保護者的な役割を果たします。恋人を世話し導こうとし、安定的で成熟した関係を追求します。ただし、相手が息苦しさを感じることがあり、対等なパートナーというより親のような役割になりがちです。',
      sihua: '化禄では長老の徳により財と福が付いてきます。化権では道徳的権威と教育的影響力を発揮します。化科では学者としての名声を得ます。化忌では頑固さとこだわりで人間関係が硬直します。',
      companion: '天機と同宮すると知恵に円熟さが加わり優れた参謀となります。太陽と出会うと名誉と知恵が結合し、天同と共にあると福と知恵の調和が実現します。',
    },
    zh: {
      name: '天梁星',
      nickname: '长者之星',
      element: '土',
      series: '天府系',
      overview: '天梁星象征智慧与庇护，代表成熟的道德品性。具有如长者般照顾和教导他人的能力，拥有在困境中岿然不动的精神力量。',
      personality: '天梁星坐命宫者成熟稳重且责任感强。自然而然地关怀他人，道德判断力出色。但可能因过于坚持原则而缺乏灵活性，有时会被认为唠叨。',
      career: '在教育、医疗、宗教、公务员等需要社会保护和服务的领域活跃。适合导师和顾问角色，在传统学术和研究方面也能取得成果。',
      relationship: '在感情中扮演保护者的角色。想要照顾和引导恋人，追求稳定成熟的关系。但对方可能感到压迫，比起平等的伴侣更可能扮演父母般的角色。',
      sihua: '化禄时凭借长者之德获得财富与福气。化权发挥道德权威和教育影响力。化科获得学者声望。化忌则因固执己见导致人际关系僵化。',
      companion: '与天机同宫则智慧之上添加成熟，成为出色的谋士。与太阳相遇则名誉与智慧结合。与天同同宫则福气与智慧和谐统一。',
    },
  },
  '七殺': {
    ko: {
      name: '칠살성(七殺星)',
      nickname: '전사의 별',
      element: '금화(金火)',
      series: '천부 계열',
      overview: '칠살성은 용기와 변혁을 상징하는 별로, 강한 독립심과 투지를 지닙니다. 금(金)과 화(火)의 이중 속성이 결합하여 날카롭고 역동적인 에너지를 품고 있으며, 도전과 개혁을 두려워하지 않습니다.',
      personality: '명궁에 칠살성이 있으면 강인하고 독립적인 성격입니다. 결단력이 있고 행동이 빠르며, 어려운 상황에서도 물러서지 않는 투지가 있습니다. 다만 성격이 급하고 거칠 수 있으며, 타인과의 타협을 어려워합니다.',
      career: '군인, 경찰, 운동선수, 기업가 등 도전과 경쟁이 필요한 분야에서 빛납니다. 기존의 것을 혁파하고 새로운 것을 개척하는 역할에 적합하며, 위기 상황에서 진가를 발휘합니다.',
      relationship: '연애에서 주도적이고 강렬한 매력을 발산합니다. 약한 모습을 보이기 싫어하며, 독립적인 연애를 추구합니다. 상대에게 많은 자유를 주는 동시에 자신도 구속받기 싫어합니다.',
      sihua: '화록이면 돌파력을 통해 재물을 획득합니다. 화권이면 군사적 권위와 조직 장악력이 강합니다. 화과면 영웅적 명성과 대중의 존경을 얻습니다. 화기가 되면 무모한 도전과 폭력적 성향의 위험이 있습니다.',
      companion: '자미(紫微)와 동궁하면 권위와 무력이 결합하여 강력한 리더십을 형성합니다. 무곡(武曲)과 만나면 결단력이 극대화되고, 파군(破軍)과 함께하면 혁명적 에너지가 폭발합니다.',
    },
    en: {
      name: 'Qi Sha Star (Seven Killings)',
      nickname: 'The Warrior Star',
      element: 'Metal-Fire',
      series: 'Tian Fu Series',
      overview: 'Qi Sha symbolizes courage and reform, possessing strong independence and fighting spirit. The combination of Metal and Fire creates sharp and dynamic energy, fearless of challenge and revolution.',
      personality: 'With Qi Sha in the Life Palace, you have a strong and independent character. Decisive with quick action, you show tenacity that never backs down from difficulty. However, you can be impatient and rough, struggling with compromise.',
      career: 'You shine in fields requiring challenge and competition — military, police, athletics, and entrepreneurship. Suited for roles that break the old and pioneer the new, you demonstrate your true worth in crisis situations.',
      relationship: 'Proactive in love with intense charm. You dislike showing weakness and pursue independent relationships. You give your partner considerable freedom while resisting being constrained yourself.',
      sihua: 'Lu acquires wealth through breakthrough power. Quan grants strong military authority and organizational control. Ke earns heroic fame and public respect. Ji risks reckless challenges and violent tendencies.',
      companion: 'With Zi Wei, authority and martial force combine for powerful leadership. With Wu Qu, decisiveness is maximized. With Po Jun, revolutionary energy explodes.',
    },
    ja: {
      name: '七殺星(しちさつせい)',
      nickname: '戦士の星',
      element: '金火',
      series: '天府系',
      overview: '七殺星は勇気と変革を象徴する星で、強い独立心と闘志を持ちます。金と火の二重属性が結合し、鋭くダイナミックなエネルギーを秘めており、挑戦と改革を恐れません。',
      personality: '命宮に七殺星がある場合、強靭で独立的な性格です。決断力があり行動が速く、困難な状況でも退かない闘志があります。ただし、性格が急で粗い面があり、他者との妥協を苦手とします。',
      career: '軍人、警察、アスリート、起業家など挑戦と競争が必要な分野で輝きます。既存のものを打破し新しいものを切り拓く役割に適しており、危機的状況で真価を発揮します。',
      relationship: '恋愛では主導的で強烈な魅力を放ちます。弱い姿を見せたがらず、独立的な恋愛を追求します。相手に多くの自由を与えると同時に自分も束縛されたくないです。',
      sihua: '化禄では突破力を通じて財を獲得します。化権では軍事的権威と組織掌握力が強いです。化科では英雄的名声と大衆の尊敬を得ます。化忌では無謀な挑戦と暴力的傾向のリスクがあります。',
      companion: '紫微と同宮すると権威と武力が結合し強力なリーダーシップを形成します。武曲と出会うと決断力が極大化され、破軍と共にあると革命的エネルギーが爆発します。',
    },
    zh: {
      name: '七杀星',
      nickname: '战士之星',
      element: '金火',
      series: '天府系',
      overview: '七杀星象征勇气与变革，具有强烈的独立性和斗志。金与火的双重属性结合，蕴含锐利而充满活力的能量，不畏挑战和改革。',
      personality: '七杀星坐命宫者性格坚毅且独立。果断行动迅速，即使在困境中也不退缩。但可能性情急躁粗犷，不善于与人妥协。',
      career: '在军人、警察、运动员、创业者等需要挑战和竞争的领域中闪耀。适合打破旧有、开拓新局面的角色，在危机时刻展现真正的价值。',
      relationship: '在感情中主动且散发强烈的魅力。不愿展示软弱的一面，追求独立的恋爱关系。给予对方充分的自由，同时自己也不愿受到约束。',
      sihua: '化禄通过突破力获取财富。化权拥有强大的军事权威和组织掌控力。化科赢得英雄声望和大众敬重。化忌则有鲁莽挑战和暴力倾向的风险。',
      companion: '与紫微同宫时权威与武力结合，形成强大的领导力。与武曲相遇则决断力达到极致。与破军同宫则革命性的能量爆发。',
    },
  },
  '破軍': {
    ko: {
      name: '파군성(破軍星)',
      nickname: '개척자의 별',
      element: '수(水)',
      series: '천부 계열',
      overview: '파군성은 파괴와 창조를 동시에 상징하는 별로, 기존 질서를 허물고 새로운 것을 만드는 혁신적인 에너지를 지닙니다. 변화와 혁신의 선봉에 서는 별이며, 안주하지 않고 끊임없이 새로운 것을 추구합니다.',
      personality: '명궁에 파군성이 있으면 혁신적이고 독창적인 성격입니다. 기존의 틀을 깨는 것을 두려워하지 않으며, 늘 새로운 것을 시도하려 합니다. 에너지가 넘치고 행동력이 강하지만, 파괴적인 면도 있어 주변을 불안하게 만들 수 있습니다.',
      career: '창업, 연구개발, 혁신 산업, 군사 분야 등에서 두각을 나타냅니다. 기존의 시스템을 개혁하거나 완전히 새로운 분야를 개척하는 역할에 적합하며, 루틴한 업무에는 맞지 않습니다.',
      relationship: '연애에서도 변화를 추구하며, 예측할 수 없는 매력이 있습니다. 지루한 관계를 견디지 못하고, 강렬하지만 불안정한 연애를 할 수 있습니다. 상대의 인생에 큰 변화를 가져다 줍니다.',
      sihua: '화록이면 혁신을 통해 새로운 부를 창출합니다. 화권이면 혁명적 권력과 개혁의 추진력을 갖습니다. 화과면 반항아적 명성과 개혁자로서의 인정을 받습니다. 화기가 되면 파괴적 변화와 혼란이 삶을 뒤흔듭니다.',
      companion: '칠살(七殺)과 함께하면 혁명적 에너지가 극대화됩니다. 무곡(武曲)과 동궁하면 파괴 후 건설하는 힘이 강해지며, 탐랑(貪狼)과 만나면 변화와 욕망이 결합하여 다이나믹한 인생을 삽니다.',
    },
    en: {
      name: 'Po Jun Star (Breaking Army)',
      nickname: 'The Pioneer Star',
      element: 'Water',
      series: 'Tian Fu Series',
      overview: 'Po Jun simultaneously symbolizes destruction and creation, possessing innovative energy that demolishes existing order to build anew. Standing at the forefront of change and innovation, it relentlessly pursues the new rather than settling.',
      personality: 'With Po Jun in the Life Palace, you are innovative and original. You don\'t fear breaking molds and constantly try new things. You overflow with energy and action, but your destructive side may unsettle those around you.',
      career: 'You excel in startups, R&D, innovation industries, and military fields. Suited for reforming existing systems or pioneering entirely new fields — routine work is not for you.',
      relationship: 'You seek change in love with unpredictable charm. Unable to endure boring relationships, your romances may be intense but unstable. You bring significant changes to your partner\'s life.',
      sihua: 'Lu creates new wealth through innovation. Quan grants revolutionary power and reform-driving force. Ke earns rebel fame and recognition as a reformer. Ji brings destructive change and chaos that shakes life\'s foundation.',
      companion: 'With Qi Sha, revolutionary energy is maximized. With Wu Qu, the power to build after destruction strengthens. With Tan Lang, change and desire combine for a dynamic life.',
    },
    ja: {
      name: '破軍星(はぐんせい)',
      nickname: '開拓者の星',
      element: '水',
      series: '天府系',
      overview: '破軍星は破壊と創造を同時に象徴する星で、既存の秩序を壊し新しいものを作る革新的なエネルギーを持ちます。変化と革新の先頭に立つ星で、安住せず絶えず新しいものを追求します。',
      personality: '命宮に破軍星がある場合、革新的で独創的な性格です。既存の枠を壊すことを恐れず、常に新しいことを試みようとします。エネルギーに溢れ行動力が強いですが、破壊的な面もあり周囲を不安にさせることがあります。',
      career: '起業、研究開発、イノベーション産業、軍事分野などで頭角を現します。既存のシステムを改革したり全く新しい分野を開拓する役割に適しており、ルーチンワークには向きません。',
      relationship: '恋愛でも変化を求め、予測できない魅力があります。退屈な関係に耐えられず、激しいが不安定な恋愛をすることがあります。相手の人生に大きな変化をもたらします。',
      sihua: '化禄では革新を通じて新たな富を創出します。化権では革命的権力と改革の推進力を持ちます。化科では反逆者的名声と改革者としての認知を得ます。化忌では破壊的変化と混乱が人生を揺さぶります。',
      companion: '七殺と共にあると革命的エネルギーが極大化されます。武曲と同宮すると破壊後に建設する力が強まり、貪狼と出会うと変化と欲望が結合しダイナミックな人生を送ります。',
    },
    zh: {
      name: '破军星',
      nickname: '开拓者之星',
      element: '水',
      series: '天府系',
      overview: '破军星同时象征破坏与创造，拥有打破既有秩序、创建新事物的革新能量。站在变革与创新的前沿，不安于现状，不断追求新生。',
      personality: '破军星坐命宫者性格革新且独创。不惧打破常规，总想尝试新事物。充满能量且行动力强，但也有破坏性的一面，可能让周围的人感到不安。',
      career: '在创业、研发、创新产业、军事领域中脱颖而出。适合改革现有体系或开辟全新领域的角色，不适合日常重复性工作。',
      relationship: '在感情中也追求变化，有着不可预测的魅力。无法忍受无聊的关系，恋爱可能激烈但不稳定。会给伴侣的人生带来重大变化。',
      sihua: '化禄通过创新创造新的财富。化权拥有革命性的权力和改革推动力。化科获得叛逆者的名声和作为改革者的认可。化忌则破坏性的变化和混乱动摇生活的根基。',
      companion: '与七杀同宫时革命性能量达到极致。与武曲同宫则破而后立的力量增强。与贪狼相遇则变化与欲望结合，过着充满活力的人生。',
    },
  },
}

// ---------------------------------------------------------------------------
// UI labels (4 languages)
// ---------------------------------------------------------------------------

export const STAR_LABELS: Record<Language, {
  pageTitle: string
  indexTitle: string
  indexSubtitle: string
  overview: string
  personality: string
  career: string
  relationship: string
  sihua: string
  companion: string
  element: string
  series: string
  ctaText: string
  ctaButton: string
  backToIndex: string
  relatedStars: string
  ziweiSeries: string
  tianfuSeries: string
}> = {
  ko: {
    pageTitle: '{name} — {nickname}',
    indexTitle: '자미두수 14주성 가이드',
    indexSubtitle: '자미두수의 14개 주성(主星)별 성격, 직업, 연애, 사화 변환을 알아보세요.',
    overview: '개요',
    personality: '성격과 기질',
    career: '직업과 재물',
    relationship: '연애와 관계',
    sihua: '사화(四化) 변환',
    companion: '동궁하는 별',
    element: '오행',
    series: '계열',
    ctaText: '내 명반에서 이 별의 위치를 직접 확인해보세요.',
    ctaButton: '무료 명반 분석하기',
    backToIndex: '14주성 목록',
    relatedStars: '관련 주성',
    ziweiSeries: '자미 계열 (紫微系)',
    tianfuSeries: '천부 계열 (天府系)',
  },
  en: {
    pageTitle: '{name} — {nickname}',
    indexTitle: '14 Main Stars of Zi Wei Dou Shu',
    indexSubtitle: 'Explore the personality, career, relationships, and Four Transformations of each main star.',
    overview: 'Overview',
    personality: 'Personality & Temperament',
    career: 'Career & Wealth',
    relationship: 'Love & Relationships',
    sihua: 'Four Transformations (Si Hua)',
    companion: 'Star Companions',
    element: 'Element',
    series: 'Series',
    ctaText: 'Discover where this star falls in your personal chart.',
    ctaButton: 'Free Chart Analysis',
    backToIndex: '14 Main Stars',
    relatedStars: 'Related Stars',
    ziweiSeries: 'Zi Wei Series',
    tianfuSeries: 'Tian Fu Series',
  },
  ja: {
    pageTitle: '{name} — {nickname}',
    indexTitle: '紫微斗数 14主星ガイド',
    indexSubtitle: '紫微斗数の14主星ごとの性格、仕事、恋愛、四化変換を詳しく解説します。',
    overview: '概要',
    personality: '性格と気質',
    career: '仕事と財運',
    relationship: '恋愛と人間関係',
    sihua: '四化変換',
    companion: '同宮する星',
    element: '五行',
    series: '系統',
    ctaText: 'あなたの命盤でこの星の位置を確認してみましょう。',
    ctaButton: '無料で命盤を分析する',
    backToIndex: '14主星一覧',
    relatedStars: '関連する主星',
    ziweiSeries: '紫微系',
    tianfuSeries: '天府系',
  },
  zh: {
    pageTitle: '{name} — {nickname}',
    indexTitle: '紫微斗数14主星指南',
    indexSubtitle: '详细了解紫微斗数14颗主星的性格、事业、感情及四化变换。',
    overview: '概述',
    personality: '性格与气质',
    career: '事业与财运',
    relationship: '爱情与关系',
    sihua: '四化变换',
    companion: '同宫星曜',
    element: '五行',
    series: '星系',
    ctaText: '查看这颗星在您的命盘中的位置。',
    ctaButton: '免费命盘分析',
    backToIndex: '14主星列表',
    relatedStars: '相关主星',
    ziweiSeries: '紫微系',
    tianfuSeries: '天府系',
  },
}
